# Generated by Django 5.0.2 on 2024-09-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='quarter',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='grading',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grading',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
