# Generated by Django 5.0.2 on 2024-04-14 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
