# Generated by Django 5.0.2 on 2024-09-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        ('users', '0006_remove_user_children_user_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_subjects',
            field=models.ManyToManyField(blank=True, to='grading.subject'),
        ),
    ]
