# Generated by Django 5.0.2 on 2024-09-23 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('occurrence_type', models.CharField(choices=[('ATIVIDADE_NAO_ENTREGUE', 'Atividade não entregue'), ('ATRASO_NA_ENTREGA', 'Atraso na entrega'), ('MAU_COMPORTAMENTO', 'Mau comportamento'), ('FALTOU_AULA', 'Faltou aula'), ('CHEGOU_ATRASADO', 'Chegou atrasado'), ('OUTRO', 'Outro')], default='OUTRO', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_occurrences', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
