# Generated by Django 5.0.3 on 2024-04-13 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_alter_classroom_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_occurrences', to=settings.AUTH_USER_MODEL),
        ),
    ]
